name: Banner
favicon: null
layout_spectrum: 0.6640153310727328
typography_spectrum: 0.5125323582906276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#70d7ff'
    - '#4b4d50'
    - '#d6d74a'
    - '#75787a'
    - '#a1a5a3'
  brandStrength: 0.6875
  lightness: 0.1320769723970443
  saturation: 0.3876037667505443
  rhythmicContrast: 0.7203273370396346
purpose: []
